#!/usr/bin/env bash
# a script that configures HAproxy in a load balancer 

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
sudo chown -R $USER:$USER /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 61360-web-01 52.201.228.204 check\n\tserver 61360-web-02 100.26.244.241 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
